# Generated by Django 5.0.1 on 2024-01-26 13:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_marked'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d', verbose_name='عکس دوم'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d', verbose_name='عکس سوم'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d', verbose_name='عکس چهارم'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False, verbose_name='تخفیف خورده'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت اصلی'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_property',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='ویژگی\u200cها'),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_star',
            field=models.BooleanField(default=False, verbose_name='پر فروش'),
        ),
        migrations.AddField(
            model_name='product',
            name='star',
            field=models.BooleanField(default=False, verbose_name='منتخب'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='قیمت با تخفیف'),
        ),
    ]
