# Generated by Django 5.0.1 on 2024-01-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_best_product_best_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='more_product',
            field=models.ManyToManyField(blank=True, null=True, to='home.product'),
        ),
    ]
