# Generated by Django 5.0.1 on 2024-02-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_orders', '0003_order_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-paid', 'closed', '-created'), 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش\u200cها'},
        ),
        migrations.AlterField(
            model_name='order',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='تمام شده'),
        ),
    ]
