# Generated by Django 5.0.1 on 2024-02-07 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='is_active',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='text',
        ),
    ]
