# Generated by Django 5.0.1 on 2024-02-07 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_options_alter_otpcode_options_and_more'),
        ('ticket', '0002_rename_is_active_ticket_status_remove_ticket_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name_plural': 'درخواست ثبت'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='text',
            field=models.TextField(default=1, verbose_name='متن درخواست'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='موضوع'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.BooleanField(default=False, verbose_name='بررسی شده'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='کاربر :'),
        ),
    ]
